# Generated by Django 4.1.13 on 2023-12-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rank_User', '0001_initial'),
        ('users', '0003_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rango_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rank_User.rangousuario'),
        ),
        migrations.DeleteModel(
            name='RangoUsuario',
        ),
    ]
