# Generated by Django 4.1.13 on 2023-12-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usuario_rango_usuario_delete_rangousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rango_usuario',
        ),
    ]
