# Generated by Django 4.1.13 on 2023-12-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usuario_contraseña_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
