# Generated by Django 4.1.13 on 2023-12-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='organizador',
        ),
    ]
