# Generated by Django 4.1.13 on 2023-12-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_inscripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
